/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Clientes;
import java.awt.Image;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DANNY
 */
public class VClientes extends javax.swing.JFrame {

    /**
     * Creates new form VClientes
     */
    public VClientes() {
        initComponents();
         ImageIcon imagen = new ImageIcon("src/IMAGENES/total.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblTotal.getWidth(),lblTotal.getHeight(),Image.SCALE_DEFAULT));
        lblTotal.setIcon(icono);
        this.repaint();
        
        
        
        //***********************************
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
         mostratabla();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        btnVercliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 269, 113, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 151, -1, -1));

        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 307, 113, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 189, -1, -1));

        btnModificar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnModificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 184, 160, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 229, -1, -1));

        tblClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cedula", "nombres", "apellidos", "correo", "telefono"
            }
        ));
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 840, 163));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo Electronico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 269, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 311, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 252, 160, -1));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel6.setText("Registro de Clientes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 337, 20));

        btnRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnGuardad.png"))); // NOI18N
        btnRegistrar.setText("Guardar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 125, 160, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazdiseño/boton menu.png"))); // NOI18N
        jButton1.setText("Menú");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 45, 97, 49));

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 151, 110, -1));

        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 191, 110, -1));

        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 231, 113, -1));

        btnVercliente.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnVercliente.setText("Ver Cliente");
        btnVercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnVercliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 370, -1, 39));

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bntClear.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 311, 160, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Next_arrow_1559.png"))); // NOI18N
        jButton4.setToolTipText("");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, -1));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        Clientes clientes = new Clientes(txtCedula.getText(), txtNombres.getText(), txtApellidos.getText(), txtCorreo.getText(), txtTelefono.getText());
        if (clientes.insertar()) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRO GUARDADO");

            mostratabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al guardar");

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int seleccionado = tblClientes.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Clientes clientes = new Clientes(txtCedula.getText(), txtNombres.getText(), txtApellidos.getText(), txtCorreo.getText(), txtTelefono.getText());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea modificar el registro", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (clientes.modificar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                    mostratabla();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked

        int seleccionado = tblClientes.getSelectedRow();
        mostrarDatos(seleccionado);
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
   

    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int seleccionado = tblClientes.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Clientes clientes = new Clientes(txtCedula.getText(), txtNombres.getText(), txtApellidos.getText(), txtCorreo.getText(), txtTelefono.getText());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar ", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (clientes.eliminar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                 mostratabla();
                 limpiarCampos();
                  
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
         validaciones vali = new validaciones();
         boolean resultado = vali.validacedula(txtCedula.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"Cedula repetida o ingreso caracteres no permitidos","Validacion de la cedula",JOptionPane.ERROR_MESSAGE);
         }
        
        
    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
       validaciones vali = new validaciones();
         boolean resultado = vali.Validarnombres(txtNombres.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras porfavor","Validacion del nombre",JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_txtNombresFocusLost

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
      validaciones vali = new validaciones();
         boolean resultado = vali.Validarnombres(txtApellidos.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras porfavor","Validacion de el apellido",JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
       validaciones vali = new validaciones();
         boolean resultado = vali.validatelefono(txtTelefono.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros porfavor","Validacion de la cedula",JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu rojo = new Menu();
        rojo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerclienteActionPerformed
    
        VServicios seviciosclientes = new  VServicios();
        seviciosclientes.setVisible(true);
        VServicios.txtCedula.setText(txtCedula.getText());
        VServicios.txtNombres.setText(txtNombres.getText());
        VServicios.txtApellidos.setText(txtApellidos.getText());
        VServicios.txtCorreo.setText(txtCorreo.getText());
        VServicios.txtTelefono.setText(txtTelefono.getText());
  
      
        this.dispose();
    }//GEN-LAST:event_btnVerclienteActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
    
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
      validaciones vali = new validaciones();
         boolean resultado = vali.ValidarMail(txtCorreo.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"El email no es valido ingrese uno valido ","Validacion del correo electronico",JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    limpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVercliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    //BUSCAR CLIENTES EN LA BASE DE DATOS
    public void mostrarResultadoBusqueda(String dato) {

        Clientes clientes = new Clientes();
        List<Clientes> lista = clientes.mostrarDatos();
        txtCedula.setText(lista.get(0).getCedula());
        txtNombres.setText(lista.get(0).getNombres());
        txtApellidos.setText(lista.get(0).getApellidos());
        txtCorreo.setText(lista.get(0).getCorreo());
        txtTelefono.setText(lista.get(0).getTelefono());

    }


    //MODIFICAR CLIENTES EN LA BASE DE DATOS
    public void mostratabla() {

        Clientes clientes = new Clientes();
        java.util.List<Clientes> lista = clientes.mostrarDatos();
        String matriz[][] = new String[lista.size()][5];
        for (int i = 0; i < lista.size(); i++) {
            matriz[i][0] = lista.get(i).getCedula();
            matriz[i][1] = lista.get(i).getNombres();
            matriz[i][2] = lista.get(i).getApellidos();
            matriz[i][3] = lista.get(i).getCorreo();
            matriz[i][4] = lista.get(i).getTelefono();
        }
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "cedula ", "nombres", "apellidos", "correo", "telefono"
                }
        ));
    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

//MOFICAR CLIENTES EN LA BASE DE DATOS
    public void limpiarCampos() {
        txtCedula.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");

    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

    //ELIMINAR EN LA BASE DE DATOS
    public void mostrarDatos(int seleccionado) {
        Clientes clientes = new Clientes();
        List<Clientes> lista = clientes.mostrarDatos();
        txtCedula.setText(lista.get(seleccionado).getCedula());
        txtNombres.setText(lista.get(seleccionado).getNombres());
        txtApellidos.setText(lista.get(seleccionado).getApellidos());
        txtCorreo.setText(lista.get(seleccionado).getCorreo());
        txtTelefono.setText(lista.get(seleccionado).getTelefono());

    }
    //ELIMINAR EN LA BASE DE DATOS

    public void mostrarvista(){
        VServicios.txtCedula.setText(txtCedula.getText());
        VServicios.txtNombres.setText(txtNombres.getText());
        VServicios.txtApellidos.setText(txtApellidos.getText());
        VServicios.txtCorreo.setText(txtCorreo.getText());
        VServicios.txtTelefono.setText(txtTelefono.getText());
    
}
}
        
