/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Empleados;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DANNY
 */
public class VEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form VEmpleados
     */
    public VEmpleados() {
        initComponents();
 ImageIcon imagen = new ImageIcon("src/IMAGENES/total.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblTotal.getWidth(),lblTotal.getHeight(),Image.SCALE_DEFAULT));
        lblTotal.setIcon(icono);
        this.repaint();        
        //*********
        btnInsertar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        mostratabla();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtRepitacontraseña = new javax.swing.JTextField();
        btnVercliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 307, 283, -1));

        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 345, 283, -1));

        cmbRol.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contador", "Mecanico", "Obrero" }));
        jPanel1.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 402, 283, -1));

        btnInsertar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnGuardad.png"))); // NOI18N
        btnInsertar.setText("Guardar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 160, -1));

        tblEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cedula", "nombres", "apellidos", "usuario", "contraseña", "repitecontraseñal", "correo", "telefono", "rol"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 502, 886, 151));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cedula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnModificar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnModificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 160, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 160, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Repita Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo Electronico:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rol");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel10.setText("Registro de Empleados");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 61, 283, -1));

        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 104, 283, -1));

        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 144, 283, -1));

        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 180, 283, -1));

        txtContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusLost(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 220, 283, -1));

        txtRepitacontraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRepitacontraseñaFocusLost(evt);
            }
        });
        jPanel1.add(txtRepitacontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 267, 283, -1));

        btnVercliente.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnVercliente.setText("Ver Empleado");
        btnVercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnVercliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, 39));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazdiseño/boton menu.png"))); // NOI18N
        jButton1.setText("Menú");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 97, 49));

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bntClear.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 160, -1));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed

        Empleados empleados = new Empleados(txtCedula.getText(), txtNombres.getText(), txtApellidos.getText(), txtUsuario.getText(), txtContraseña.getText(), txtRepitacontraseña.getText(), txtCorreo.getText(), txtTelefono.getText(), cmbRol.getSelectedItem().toString());
        if (empleados.insertar()) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRO GUARDADO");
            mostratabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al guardar");

        }

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int seleccionado = tblEmpleados.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Empleados empleados = new Empleados(txtCedula.getText(), txtNombres.getText(), txtApellidos.getText(), txtUsuario.getText(), txtContraseña.getText(), txtRepitacontraseña.getText(), txtCorreo.getText(), txtTelefono.getText(), cmbRol.getSelectedItem().toString());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea modificar el registro", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (empleados.modificar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                    mostratabla();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        int seleccionado = tblEmpleados.getSelectedRow();
        mostrarDatos(seleccionado);


    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int seleccionado = tblEmpleados.getSelectedRow();
        int respuesta = 0;
        Empleados empleados = new Empleados(txtCedula.getText(), txtNombres.getText(), txtApellidos.getText(), txtUsuario.getText(), txtContraseña.getText(), txtRepitacontraseña.getText(), txtCorreo.getText(), txtTelefono.getText(), cmbRol.getSelectedItem().toString());
        if (seleccionado != -1) {

            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar ", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (empleados.eliminar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                    mostratabla();
                    limpiarCampos();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        validaciones vali = new validaciones();
        boolean resultado = vali.validacedula(txtCedula.getText());
        if (resultado == false) {
            JOptionPane.showMessageDialog(rootPane, "Cedula repetida o ingreso caracteres no permitidos", "Validacion de la cedula", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
        validaciones vali = new validaciones();
        boolean resultado = vali.Validarnombres(txtNombres.getText());
        if (resultado == false) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras porfavor", "Validacion del nombre", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_txtNombresFocusLost

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        validaciones vali = new validaciones();
        boolean resultado = vali.Validarnombres(txtApellidos.getText());
        if (resultado == false) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras porfavor", "Validacion de el apellido", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusLost
        validaciones vali = new validaciones();
        boolean resultado = vali.validaContrasena(txtContraseña.getText());
        if (resultado == false) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese una contraseña almenos un numero y una mayusculas", "Validacion de contraseña", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtContraseñaFocusLost

    private void txtRepitacontraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRepitacontraseñaFocusLost
        validaciones validacion = new validaciones();
        boolean resultado = validacion.validaRepiteClave(txtContraseña.getText(), txtRepitacontraseña.getText());
        if (resultado == false) {
            JOptionPane.showMessageDialog(rootPane, "La clave debe ser igual a  la anterior", "Validacion de repita clave", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtRepitacontraseñaFocusLost

    private void btnVerclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerclienteActionPerformed

        VServicios seviciosvehiculos = new VServicios();
        seviciosvehiculos.setVisible(true);
        VServicios.txtNombres2.setText(txtNombres.getText());
        VServicios.txtApellidos2.setText(txtApellidos.getText());
       
        this.dispose();
    }//GEN-LAST:event_btnVerclienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu rojo = new Menu();
        rojo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
 validaciones vali = new validaciones();
        boolean resultado = vali.validaNombreusuario(txtUsuario.getText());
        if (resultado == false) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese almenos un numero y una mayusculas", "Validacion de contraseña", JOptionPane.ERROR_MESSAGE);
        }       
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
  validaciones vali = new validaciones();
         boolean resultado = vali.ValidarMail(txtCorreo.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"El email no es valido ingrese uno valido ","Validacion del correo electronico",JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
   validaciones vali = new validaciones();
         boolean resultado = vali.validatelefono(txtTelefono.getText());
         if (resultado == false){
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros porfavor","Validacion del Telefono",JOptionPane.ERROR_MESSAGE);
         }
        
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       limpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVercliente;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRepitacontraseña;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    //BUSCAR CLIENTES EN LA BASE DE DATOS
    public void mostrarResultadoBusqueda(String dato) {

        Empleados empleados = new Empleados();
        List<Empleados> lista = empleados.mostrarDatos();
        txtCedula.setText(lista.get(0).getCedula());
        txtNombres.setText(lista.get(0).getNombres());
        txtApellidos.setText(lista.get(0).getApellidos());
        txtUsuario.setText(lista.get(0).getUsuario());
        txtContraseña.setText(lista.get(0).getNombres());
        txtRepitacontraseña.setText(lista.get(0).getRepita_contraseña());
        txtCorreo.setText(lista.get(0).getCorreo());
        txtTelefono.setText(lista.get(0).getTelefono());
        cmbRol.setSelectedItem(lista.get(0).getRol());

    }
//BUSCAR CLIENTES EN LA BASE DE DATOS

    //MODIFICAR CLIENTES EN LA BASE DE DATOS
    public void mostratabla() {

        Empleados empleados = new Empleados();
        java.util.List<Empleados> lista = empleados.mostrarDatos();
        String matriz[][] = new String[lista.size()][9];
        for (int i = 0; i < lista.size(); i++) {
            matriz[i][0] = lista.get(i).getCedula();
            matriz[i][1] = lista.get(i).getNombres();
            matriz[i][2] = lista.get(i).getApellidos();
            matriz[i][3] = lista.get(i).getUsuario();
            matriz[i][4] = lista.get(i).getContraseña();
            matriz[i][5] = lista.get(i).getRepita_contraseña();
            matriz[i][6] = lista.get(i).getCorreo();
            matriz[i][7] = lista.get(i).getTelefono();
            matriz[i][8] = lista.get(i).getRol();

        }
        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "cedula", "nombres", "apellidos", "usuario", "contraseña", "repitecontraseñal", "correo", "telefono", "rol"
                }
        ));
    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

//MOFICAR CLIENTES EN LA BASE DE DATOS
    public void limpiarCampos() {
        txtCedula.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtRepitacontraseña.setText("");

    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

    //ELIMINAR EN LA BASE DE DATOS
    public void mostrarDatos(int seleccionado) {
        Empleados empleados = new Empleados();
        List<Empleados> lista = empleados.mostrarDatos();
        txtCedula.setText(lista.get(seleccionado).getCedula());
        txtNombres.setText(lista.get(seleccionado).getNombres());
        txtApellidos.setText(lista.get(seleccionado).getApellidos());
        txtUsuario.setText(lista.get(seleccionado).getUsuario());
        txtContraseña.setText(lista.get(seleccionado).getContraseña());
        txtRepitacontraseña.setText(lista.get(seleccionado).getRepita_contraseña());
        txtCorreo.setText(lista.get(seleccionado).getCorreo());
        txtTelefono.setText(lista.get(seleccionado).getTelefono());
        cmbRol.setSelectedItem(lista.get(seleccionado).getRol());

    }
    //ELIMINAR EN LA BASE DE DATOS

}
