/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Repuestos;
import Conexion.PgConect;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DANNY
 */
public class VRepuestos extends javax.swing.JFrame {

    /**
     * Creates new form VRepuestos
     */
    public VRepuestos() {
        initComponents();
         ImageIcon imagen = new ImageIcon("src/IMAGENES/total.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblTotal.getWidth(),lblTotal.getHeight(),Image.SCALE_DEFAULT));
        lblTotal.setIcon(icono);
        this.repaint();
        //***************
        mostratabla();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepuestos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imagenesa = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        btnFoto = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblRuta = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVercliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del repuesto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        tblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "nombres", "descripcion", "precio", "cantidadl", "foto"
            }
        ));
        tblRepuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRepuestosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRepuestos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 780, 166));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel6.setText("Registro de Repuestos ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 17, -1, -1));

        imagenesa.setForeground(new java.awt.Color(51, 51, 0));
        imagenesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imagenesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 138, 176));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 156, -1));

        btnFoto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnFoto.setForeground(new java.awt.Color(0, 0, 255));
        btnFoto.setText("Cargar Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 156, -1));

        lblRuta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 138, 25));
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 156, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 156, -1));
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 156, -1));

        btnRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnGuardad.png"))); // NOI18N
        btnRegistrar.setText("Guardar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 150, -1));

        btnModificar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnModificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 150, -1));

        btnVercliente.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnVercliente.setText("Ver Repuesto");
        btnVercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnVercliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazdiseño/boton menu.png"))); // NOI18N
        jButton1.setText("Menú");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 97, 49));

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bntClear.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 150, -1));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        Repuestos repuestos = new Repuestos(txtCodigo.getText(), txtNombres.getText(), txtDescripcion.getText(), txtPrecio.getText(), txtCantidad.getText(), lblRuta.getText());
        if (repuestos.insertar()) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRO GUARDADO");

            mostratabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al guardar");

        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Seleccione la foto de la persona");
        //showOpenDialog PARA SABER SI SE HABRIO LA VENTANA Y SE SELECCIONO EL ARCHIVO
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            File archivo = new File(file.getSelectedFile().toString());
            String dest = "src\\main\\java\\IMAGENES\\" + archivo.getName();
         
            String orig = archivo.getPath();
            String imagen = archivo.getName();

            ImageIcon icon = new ImageIcon(orig);
            ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(imagenesa.getWidth(), imagenesa.getHeight(), Image.SCALE_DEFAULT));
            imagenesa.setText(null);
            imagenesa.setIcon(icono);

            if (archivo.exists()) {
                try {
                    InputStream in = new FileInputStream(orig);
                    OutputStream out = new FileOutputStream(dest);
                    lblRuta.setText(dest);
                    // We use a buffer for the copy (Usamos un buffer para la copia).
                    byte[] buf = new byte[1024];
                    int len;
                    while ((len = in.read(buf)) > 0) {
                        out.write(buf, 0, len);
                    }
                    in.close();
                    out.close();

                } catch (IOException ioe) {
                    ioe.printStackTrace();

                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe el archivo");
            }

        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        int seleccionado = tblRepuestos.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Repuestos repuestos = new Repuestos(txtCodigo.getText(), txtNombres.getText(), txtDescripcion.getText(), txtPrecio.getText(), txtCantidad.getText(), lblRuta.getText());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea modificar el registro", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (repuestos.modificar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                    mostratabla();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int seleccionado = tblRepuestos.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Repuestos repuestos = new Repuestos(txtCodigo.getText(), txtNombres.getText(), txtDescripcion.getText(), txtPrecio.getText(), txtCantidad.getText(), lblRuta.getText());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar ", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (repuestos.eliminar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");

                    mostratabla();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblRepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRepuestosMouseClicked
        int seleccionado = tblRepuestos.getSelectedRow();
        mostrarDatos(seleccionado);
    }//GEN-LAST:event_tblRepuestosMouseClicked

    private void btnVerclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerclienteActionPerformed

        VServicios seviciosclientes = new VServicios();
        seviciosclientes.setVisible(true);
        VServicios.txtCodigo.setText(txtCodigo.getText());
        VServicios.txtNombres1.setText(txtNombres.getText());
        VServicios.txtDescripcion.setText(txtDescripcion.getText());
        VServicios.txtPrecio.setText(txtPrecio.getText());
        VServicios.txtCantidad.setText(txtCantidad.getText());

        this.dispose();
    }//GEN-LAST:event_btnVerclienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu rojo = new Menu();
        rojo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRepuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRepuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVercliente;
    private javax.swing.JLabel imagenesa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblRepuestos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    //MODIFICAR CLIENTES EN LA BASE DE DATOS
    public void mostratabla() {

        Repuestos repuestos = new Repuestos();
        java.util.List<Repuestos> lista = repuestos.mostrarDatos();
        String matriz[][] = new String[lista.size()][6];
        for (int i = 0; i < lista.size(); i++) {
            matriz[i][0] = lista.get(i).getCodigo();
            matriz[i][1] = lista.get(i).getNombres();
            matriz[i][2] = lista.get(i).getDescripcion();
            matriz[i][3] = lista.get(i).getPrecio();
            matriz[i][4] = lista.get(i).getCantidad();
            matriz[i][5] = lista.get(i).getImagenesa();

        }
        tblRepuestos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "codigo ", "nombres", "descripcion", "precio", "cantidad", "foto"
                }
        ));
    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

//MOFICAR CLIENTES EN LA BASE DE DATOS
    public void limpiarCampos() {
        txtCodigo.setText("");
        txtNombres.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        lblRuta.setText("");

    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

    //ELIMINAR EN LA BASE DE DATOS
    public void mostrarDatos(int seleccionado) {
        Repuestos repuestos = new Repuestos();
        List<Repuestos> lista = repuestos.mostrarDatos();
        txtCodigo.setText(lista.get(seleccionado).getCodigo());
        txtNombres.setText(lista.get(seleccionado).getNombres());
        txtDescripcion.setText(lista.get(seleccionado).getDescripcion());
        txtPrecio.setText(lista.get(seleccionado).getPrecio());
        txtCantidad.setText(lista.get(seleccionado).getCantidad());
        ImageIcon icon = new ImageIcon(lista.get(seleccionado).getImagenesa());
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(imagenesa.getWidth(), imagenesa.getHeight(), Image.SCALE_DEFAULT));
        imagenesa.setText(null);
        imagenesa.setIcon(icono);

    }
    //ELIMINAR EN LA BASE DE DATOS

    public void mostrarResultadoBusqueda(String dato) {

        Repuestos repuestos = new Repuestos();
        List<Repuestos> lista = repuestos.mostrarDatos();
        txtCodigo.setText(lista.get(0).getCodigo());
        txtNombres.setText(lista.get(0).getNombres());
        txtDescripcion.setText(lista.get(0).getDescripcion());
        txtPrecio.setText(lista.get(0).getPrecio());
        txtCantidad.setText(lista.get(0).getCantidad());
        ImageIcon icon = new ImageIcon(lista.get(0).getImagenesa());
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(imagenesa.getWidth(), imagenesa.getHeight(), Image.SCALE_DEFAULT));
        imagenesa.setText(null);
        imagenesa.setIcon(icono);

    }
    
    public void mostrarvista(){
        VServicios.txtCodigo.setText(txtCodigo.getText());
        VServicios.txtNombres1.setText(txtNombres.getText());
        VServicios.txtDescripcion.setText(txtDescripcion.getText());
        VServicios.txtPrecio.setText(txtPrecio.getText());
        VServicios.txtCantidad.setText(txtCantidad.getText());
    }

}
