
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Vehiculos;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DANNY
 */
public class VVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form VVehiculo
     */
    public VVehiculo() {
        initComponents();
        
         ImageIcon imagen = new ImageIcon("src/IMAGENES/total.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblTotal.getWidth(),lblTotal.getHeight(),Image.SCALE_DEFAULT));
        lblTotal.setIcon(icono);
        this.repaint();
        //*******************
        btnGuardarRegistro.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        mostratabla();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarRegistro = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        imagenesa = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        lblRuta = new javax.swing.JLabel();
        btnVercliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Color:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 100, -1));

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, -1));
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        jLabel5.setText("Registro Vehiculos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        btnGuardarRegistro.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnGuardarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnGuardad.png"))); // NOI18N
        btnGuardarRegistro.setText("Guardar ");
        btnGuardarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 150, -1));

        btnModificar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnModificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "placa", "modelo", "color", "marca", "tipo", "foto"
            }
        ));
        tblVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 651, 140));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/btnEliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 150, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 100, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        cmbTipo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auto", "camion", "camioneta", "moto" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 100, -1));

        imagenesa.setForeground(new java.awt.Color(51, 51, 0));
        imagenesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(imagenesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 138, 176));

        btnFoto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnFoto.setForeground(new java.awt.Color(0, 0, 255));
        btnFoto.setText("Cargar Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        lblRuta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 138, 25));

        btnVercliente.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnVercliente.setText("Ver Vehiculo");
        btnVercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnVercliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazdiseño/boton menu.png"))); // NOI18N
        jButton1.setText("Menú");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 97, 49));

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/bntClear.png"))); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 150, -1));
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnGuardarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRegistroActionPerformed

        Vehiculos vehiculos = new Vehiculos(txtPlaca.getText(), txtModelo.getText(), txtColor.getText(), txtMarca.getText(), cmbTipo.getSelectedItem().toString(), lblRuta.getText());
        if (vehiculos.insertar()) {
            JOptionPane.showMessageDialog(rootPane, "REGISTRO GUARDADO");

            mostratabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error al guardar");

        }

    }//GEN-LAST:event_btnGuardarRegistroActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int seleccionado = tblVehiculos.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Vehiculos vehiculos = new Vehiculos(txtPlaca.getText(), txtModelo.getText(), txtColor.getText(), txtMarca.getText(), cmbTipo.getSelectedItem().toString(), lblRuta.getText());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea modificar el registro", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (vehiculos.modificar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                    mostratabla();
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculosMouseClicked

        int seleccionado = tblVehiculos.getSelectedRow();
        mostrarDatos(seleccionado);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

    }//GEN-LAST:event_tblVehiculosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int seleccionado = tblVehiculos.getSelectedRow();
        int respuesta = 0;

        if (seleccionado != -1) {
            Vehiculos vehiculos = new Vehiculos(txtPlaca.getText(), txtModelo.getText(), txtColor.getText(), txtMarca.getText(), cmbTipo.getSelectedItem().toString(), lblRuta.getText());
            respuesta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea eliminar ", "mesanje de confirmacion", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {

                if (vehiculos.eliminar()) {
                    JOptionPane.showMessageDialog(rootPane, "Registro guardado");
                    mostratabla();
                    limpiarCampos();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Seleccione la foto de la persona");
        //showOpenDialog PARA SABER SI SE HABRIO LA VENTANA Y SE SELECCIONO EL ARCHIVO
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            File archivo = new File(file.getSelectedFile().toString());
            String dest = "src\\main\\java\\IMAGENES\\" + archivo.getName();
            String orig = archivo.getPath();
            String imagen = archivo.getName();

            ImageIcon icon = new ImageIcon(orig);
            ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(imagenesa.getWidth(), imagenesa.getHeight(), Image.SCALE_DEFAULT));
            imagenesa.setText(null);
            imagenesa.setIcon(icono);

            if (archivo.exists()) {
                try {
                    InputStream in = new FileInputStream(orig);
                    OutputStream out = new FileOutputStream(dest);
                    lblRuta.setText(dest);
                    // We use a buffer for the copy (Usamos un buffer para la copia).
                    byte[] buf = new byte[1024];
                    int len;
                    while ((len = in.read(buf)) > 0) {
                        out.write(buf, 0, len);
                    }
                    in.close();
                    out.close();

                } catch (IOException ioe) {
                    ioe.printStackTrace();

                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe el archivo");
            }

        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnVerclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerclienteActionPerformed

        VServicios seviciosvehiculos = new VServicios();
        seviciosvehiculos.setVisible(true);
        VServicios.txtPlaca.setText(txtPlaca.getText());
        VServicios.txtMarca.setText(txtMarca.getText());
        VServicios.txtColor.setText(txtColor.getText());
        VServicios.txtModelo.setText(txtModelo.getText());
        this.dispose();
    }//GEN-LAST:event_btnVerclienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu rojo = new Menu();
        rojo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     limpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnGuardarRegistro;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVercliente;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel imagenesa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
//BUSCAR CLIENTES EN LA BASE DE DATOS
    public void mostrarResultadoBusqueda(String dato) {

        Vehiculos vehiculos = new Vehiculos();
        List<Vehiculos> lista = vehiculos.mostrarDatos();
        txtPlaca.setText(lista.get(0).getPlaca());
        txtModelo.setText(lista.get(0).getModelo());
        txtColor.setText(lista.get(0).getColor());
        txtMarca.setText(lista.get(0).getMarca());
        cmbTipo.setSelectedItem(lista.get(0).getTipo());
        ImageIcon icon = new ImageIcon(lista.get(0).getFoto());
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(imagenesa.getWidth(), imagenesa.getHeight(), Image.SCALE_DEFAULT));
        imagenesa.setText(null);
        imagenesa.setIcon(icono);

    }
//BUSCAR CLIENTES EN LA BASE DE DATOS

    //MODIFICAR CLIENTES EN LA BASE DE DATOS
    public void mostratabla() {

        Vehiculos vehiculos = new Vehiculos();
        java.util.List<Vehiculos> lista = vehiculos.mostrarDatos();
        String matriz[][] = new String[lista.size()][6];
        for (int i = 0; i < lista.size(); i++) {
            matriz[i][0] = lista.get(i).getPlaca();
            matriz[i][1] = lista.get(i).getModelo();
            matriz[i][2] = lista.get(i).getColor();
            matriz[i][3] = lista.get(i).getMarca();
            matriz[i][4] = lista.get(i).getTipo();
            matriz[i][5] = lista.get(i).getFoto();

        }
        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "placa ", "modelo", "color", "marca", "tipo", "foto"
                }
        ));
    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

//MOFICAR CLIENTES EN LA BASE DE DATOS
    public void limpiarCampos() {
        txtPlaca.setText("");
        txtModelo.setText("");
        txtColor.setText("");
        txtMarca.setText("");
        lblRuta.setText("");
    }
//MOFICAR CLIENTES EN LA BASE DE DATOS

    //ELIMINAR EN LA BASE DE DATOS
    public void mostrarDatos(int seleccionado) {
        Vehiculos vehiculos = new Vehiculos();
        List<Vehiculos> lista = vehiculos.mostrarDatos();
        txtPlaca.setText(lista.get(seleccionado).getPlaca());
        txtModelo.setText(lista.get(seleccionado).getModelo());
        txtColor.setText(lista.get(seleccionado).getColor());
        txtMarca.setText(lista.get(seleccionado).getMarca());
        cmbTipo.setSelectedItem(lista.get(seleccionado).getTipo());
        ImageIcon icon = new ImageIcon(lista.get(seleccionado).getFoto());
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(imagenesa.getWidth(), imagenesa.getHeight(), Image.SCALE_DEFAULT));
        imagenesa.setText(null);
        imagenesa.setIcon(icono);
    }
    //ELIMINAR EN LA BASE DE DATOS

     public void mostrarvista(){
         
        
        
        VServicios.txtPlaca.setText(txtPlaca.getText());
        VServicios.txtMarca.setText(txtMarca.getText());
        VServicios.txtColor.setText(txtColor.getText());
        VServicios.txtModelo.setText(txtModelo.getText());
       
     }
}
